% import_simiodata.m - script file to allow the user to alter the path to
% the csv files generated by simio, called from the main user interface 


% Give the user some feedback so they know where the fiels currently are
% and can hence decide which or both to change 
disp('The initial path to the feed rate SIMIO File is:')
disp(path2feedrtsimiocsv)
disp('The Initial Path to the buffer size SIMIO File is:')
disp(path2palletsimiocsv)

% offer user a dialogue box asking if they want to select a new feed rate
% experiment file 
feed_selection = questdlg('Select New Feedrate Simio Data?','Legoline File Selection','Yes','No','Yes'); 
% if they choose to change it then run this fragment 
if strcmp(feed_selection,'Yes') == 1
    [FILENAME, PATHNAME, FILTERINDEX] = uigetfile('*.csv', 'Please Select a Feedrate Results File');
    if FILTERINDEX == 1
        % Filterindex is a binary varibale 1 if a path is successfully
        % entered else it comes back as a zero and the operation is
        % terminated 
        path2feedrtsimiocsv = [PATHNAME,FILENAME];
        disp('SIMIO Feed Rate Path Updated')
    else
        % else tell the suer that they have chosen not to change anything 
        disp('User Selected not to update feed path ')
    end % end of if needing update 
end % end of if Yes statement 


% offer user a dialogue box asking if they want to select a new buffer size
% experiment file 
pallet_selection = questdlg('Select New Pallet Buffer Size Simio Data?','Legoline File Selection','Yes','No','Yes'); 
if strcmp(pallet_selection,'Yes') == 1
    [FILENAME, PATHNAME, FILTERINDEX] = uigetfile('*.csv', 'Please Select a Pallet Buffer Size Results File');
    if FILTERINDEX == 1
        % Filterindex is a binary varibale 1 if a path is successfully
        % entered else it comes back as a zero and the operation is
        % terminated 
        path2palletsimiocsv = [PATHNAME,FILENAME];
        disp('SIMIO Pallet Buffer Size Path Updated')
    else
        % else tell the suer that they have chosen not to change anything 
        disp('User Selected not to update buffer size path ')
    end % end of if needing update 
end % end of if Yes statement 


% Perform some housekeeping on local  variabls that have no use elsewhere
clear FILENAME
clear PATHNAME
clear FILTERINDEX
clear feed_selection
clear pallet_selection
% a few messages for the user to elt them know everything has gone OK and
% tell them where hey set the file to 
disp('The New Feed Rate Experiment Path is:')
disp(path2feedrtsimiocsv)
disp('The New Pallet Buffer Size Experiment Path is:')
disp(path2palletsimiocsv)